flatshare/urls.py
from django.urls import path
from flatshare import views

app_name = 'flatshare'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('flats/', views.list_flats, name="list_flats"),
    path('flats/<slug:flat_slug>/', views.show_flat, name='show_flat'),
    path('flats/<slug:flat_slug>/like/', views.like_flat, name='like_flat'),
    path('users/<slug:user_slug>/', views.view_profile, name='view_profile'),
    path('users/<slug:user_slug>/change_password/', views.change_password, name='change_password'),
    path('my_matches/', views.my_matches, name='my_matches'),
    path('my_matches/<slug:user_slug>/like/', views.like_profile, name='my_matches'),
    path('my_matches/<slug:flat_slug>/unlike/', views.unlike_flat, name='unlike_flat'),
    path('add_flat/', views.add_flat, name='add_flat'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

flatshare_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from flatshare import views

urlpatterns = [
    path('', views.index, name='index'),
    path('flatshare/', include('flatshare.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flatshare/models.py
import uuid

from django.template.defaultfilters import slugify
from django.utils.timezone import now
from django.db import models
from django.contrib.auth.models import User


class Address(models.Model):
    address_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    flat_no = models.CharField(max_length=5)
    house_no = models.IntegerField(default=1)
    street = models.CharField(max_length=99)
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    postcode = models.CharField(max_length=10)
    country = models.CharField(max_length=60)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.flat_no + ' ' + str(self.house_no) + ' ' + self.street + ' ' + self.city + ' ' + self.province


class Flat(models.Model):
    NAME_MAX_CHAR = 128
    name = models.CharField(max_length=NAME_MAX_CHAR)
    flat_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    address = models.OneToOneField(Address, on_delete=models.CASCADE, null=True)
    rent = models.IntegerField(default=1)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None, related_name="owned_flat_set")
    description = models.TextField(max_length=500)
    available_from = models.DateField(default=now)
    save_location: str = ""
    image1 = models.ImageField(upload_to=save_location, blank=True, null=True)
    image2 = models.ImageField(upload_to=save_location, blank=True, null=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.flat_id)
        self.save_location = "{0}_images".format(self.slug)
        super(Flat, self).save(*args, **kwargs)

    def __str__(self):
        return self.name + ' ' + str(self.address)


class UserProfile(models.Model):
    NAME_MAX_CHAR = 128
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    FirstName = models.CharField(max_length=NAME_MAX_CHAR, unique=False)
    LastName = models.CharField(max_length=NAME_MAX_CHAR, unique=False)
    picture = models.ImageField(upload_to='{0}/profile_images'.format(str(id(user))), blank=True)
    phone_no = models.IntegerField(unique=True, blank=True)
    bio = models.CharField(max_length=500,unique=False,default="")
    age = models.IntegerField(default=18)
    liked_flats = models.ManyToManyField(Flat, related_name="likers", blank=True)
    liked_users = models.ManyToManyField(User, related_name="liked_by_set", blank=True)
    slug = models.SlugField(blank=True)

    # owned_flat_set: get via flats model

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.FirstName + " " + self.LastName

class Match(models.Model):
    match_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    m_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    m_flat = models.ForeignKey(Flat, on_delete=models.CASCADE, related_name='+')
    m_owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='+', null=True)

    class Meta:
        verbose_name_plural = 'Matches'

    def __str__(self):
        return str(self.m_user) + " " + str(self.m_flat)

flatshare/forms.py
from django import forms
from django.utils.timezone import now
from flatshare.models import Flat, Address, UserProfile
from django.contrib.auth.models import User


class AddAddressForm(forms.ModelForm):
    help_text = ("Please enter an address for your flat")
    flat_no = forms.CharField()
    house_no = forms.IntegerField()
    street = forms.CharField()
    city = forms.CharField()
    province = forms.CharField()
    postcode = forms.CharField()
    country = forms.CharField()

    class Meta:
        model = Address
        fields = ('flat_no', 'house_no', 'street', 'city', 'province', 'postcode', 'country')


class AddFlatForm(forms.ModelForm, ):
    help_text = ("Please enter flat details.")
    name = forms.CharField()
    rent = forms.IntegerField(initial=0)
    description = forms.TextInput()
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    available_from = forms.DateField(initial=now())
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Flat
        fields = ('name', 'rent', 'description', 'image1', 'image2', 'available_from')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('FirstName', 'LastName', 'picture', 'phone_no', 'age')


class ChangePasswordForm(forms.ModelForm):
    help_text = ("Please enter a new password.")
    new_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('password',)

flatshare/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from flatshare.models import Flat, UserProfile, Match
from flatshare.forms import AddFlatForm, UserProfileForm, UserForm, AddAddressForm, ChangePasswordForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import reverse
from django.contrib.auth.models import User


def index(request):
    return render(request, 'flatshare/index.html')


def about(request):
    context_dict = {}
    if request.user.is_authenticated:
        context_dict["user_authenticated"] = True
        user = UserProfile.objects.get(user=request.user)
        context_dict['user'] = user
    return render(request, 'flatshare/about.html', context=context_dict)


def contact(request):
    context_dict = {}
    if request.user.is_authenticated:
        context_dict["user_authenticated"] = True
        user = UserProfile.objects.get(user=request.user)
        context_dict['user'] = user
    return render(request, 'flatshare/contact.html', context=context_dict)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        print(password)
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('flatshare:index'))
            else:
                return HttpResponse('Your flatshare account is disabled')
        else:
            print(f"invalid login details: {username}, {password}".format(username=username, password=password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'flatshare/login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('flatshare:index'))


def signup(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
            user = authenticate(username=user_form.cleaned_data['username'],
                                password=user_form.cleaned_data['password'], )
            login(request, user)
            return redirect(reverse('flatshare:index'))
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'flatshare/signup.html',
                  context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

@login_required()
def change_password(request, user_slug):
    u = request.user
    errors = None
    password_form = ChangePasswordForm(request.POST)
    if password_form.is_valid() and u.check_password(password_form.cleaned_data['password']):
        u.set_password(password_form.cleaned_data['new_password'])
        u.save()
        redirect(reverse('flatshare:login'))
    else:
        errors = password_form.errors
    return render(request, 'flatshare/change_password.html', context={'user': request.user, 'password_form' : password_form, 'errors': errors})


@login_required()
def view_profile(request, user_slug):
    context_dict = {}
    try:
        user = User.objects.get(username=user_slug)
        user_profile = UserProfile.objects.get(user=user)
        context_dict['user_profile'] = user_profile
        context_dict['owned_flats'] = user_profile.user.owned_flat_set.all()
    except UserProfile.DoesNotExist:
        context_dict['user_profile'] = None
    return render(request, 'flatshare/user.html', context=context_dict)


@login_required()
def like_profile(request, user_slug):
    liked_user = UserProfile.objects.get(slug=user_slug)
    if liked_user not in request.user.userprofile.liked_users.all():
        request.user.userprofile.liked_users.add(liked_user.user)
        Match.objects.create(m_user=liked_user, m_flat=liked_user.liked_flats.get(owner=request.user),
                             m_owner=request.user.userprofile)
    return redirect(reverse('flatshare:my_matches'))


@login_required
def my_matches(request):
    context_dict = {}
    flat_matches = []
    try:
        context_dict["likes"] = request.user.userprofile.liked_flats.all()
        for match in Match.objects.filter(m_user=request.user.userprofile).all():
            flat_matches.append(match)
        for match in Match.objects.filter(m_owner=request.user.userprofile).all():
            flat_matches.append(match)
        context_dict['matches'] = flat_matches
        flat_likers = Flat.objects.get(owner=request.user).likers.all()
        context_dict['likers'] = flat_likers
    except Flat.DoesNotExist:
        pass
    return render(request, 'flatshare/matches.html', context=context_dict)


@login_required()
def add_flat(request):
    if request.user.is_authenticated:
        address_form = AddAddressForm()
        form = AddFlatForm()

        if request.method == 'POST':
            address_form = AddAddressForm(request.POST)
            form = AddFlatForm(request.POST)

            if all((address_form.is_valid(), form.is_valid())):
                address = address_form.save(commit=True)
                print(address)
                flat = form.save(commit=False)
                print(flat)
                flat.address = address
                flat.owner = request.user
                flat.save()
                return redirect('/')
            else:
                print('YIKES')
                print(address_form.errors)
                print(form.errors)
        return render(request, 'flatshare/add_flat.html', {'address_form': address_form, 'form': form, })
    else:
        return HttpResponse("please log in first!")


def show_flat(request, flat_slug):
    context_dict = {}
    try:
        flat = Flat.objects.get(slug=flat_slug)
        context_dict['flat'] = flat
    except Flat.DoesNotExist:
        context_dict['flat'] = None
    return render(request, 'flatshare/flat.html', context=context_dict)


@login_required()
def like_flat(request, flat_slug):
    liked_flat = Flat.objects.get(slug=flat_slug)
    if liked_flat not in request.user.userprofile.liked_flats.all() and liked_flat not in request.user.owned_flat_set.all():
        request.user.userprofile.liked_flats.add(liked_flat)
    return redirect(reverse('flatshare:show_flat', args=[liked_flat.slug]))


@login_required()
def unlike_flat(request, flat_slug):
    unliked_flat = Flat.objects.get(slug=flat_slug)
    if unliked_flat in request.user.userprofile.liked_flats.all() and unliked_flat not in request.user.owned_flat_set.all():
        request.user.userprofile.liked_flats.remove(unliked_flat)
    return redirect(reverse('flatshare:my_matches'))


def list_flats(request):
    context_dict = {}
    SELECTED_ORDER = 'rent'
    flat_list = Flat.objects.order_by(SELECTED_ORDER)
    context_dict['flats'] = flat_list

    return render(request, 'flatshare/flats.html', context=context_dict)

templates/flatshare/about.html
<!DOCTYPE html>
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>Flatshare - About</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
{% endblock %}

{% block body_block %}
    <h1>About Us</h1>
    <img class = "about-image" src="{% static 'images/apartment2.jpg' %}" alt="Flat"/>
    <div class = "main-about">
        <h3>The website is a flat share finding website, with two types of users, people looking for rooms and people looking for flatmates. The people looking for flatmates will post details about their flat and will then be able to search through users looking to live in the area of their flat and like people who they think would be a good fit for them. The users looking for a room would post details of themselves and the area they would like to stay in, they would then be able to like flats that they’d like to stay in. If the user and flat matched, then a notification would be sent to both with details for contacting each other.</h3>
    </div>
{% endblock %}

templates/flatshare/add_flat.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_block %}
    <title>flatshare - add flat</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_flat.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock %}

{% block body_block %}
<dvi class='head'>
</dvi>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 style="font-family: 'Trade Winds',cursive;">Add a Flat</h1>
            <hr class="mt-0 mb-4">
            <div>
                <form id="add_flat_form" method="post" action="/flatshare/add_flat/">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {% for hidden in address_form.hidden_fields %}
                        <div class= "col-6">
                            {{ hidden|as_crispy_field }}
                        </div>
                    {% endfor %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in address_form.visible_fields %}
                        <div class= "col-6">
                            {{ field|as_crispy_field }}
                        </div>
                    {% endfor %}
                    <input type="submit" name="submit" value="Add Flat" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/flatshare/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Satisfy|Trade+Winds&display=swap" rel="stylesheet">
        {% block head_block %}
            <title>
                Flatshare - Base          
            </title>
        {% endblock %}
    </head>
    <body>
        <div class="header">
            <div class="nav_bar">
                <ul>
                    <li style = "padding-bottom:0"><h1 class = "logo">FLATSHARE</h1></li>
                    <li><a href="{% url 'flatshare:index' %}">Home</a></li>
                    <li><a href="{% url 'flatshare:list_flats' %}">Available Flats</a></li>
                    <li><a href="{% url 'flatshare:add_flat' %}">Add a New Flat</a></li>
                    <li><a href="{% url 'flatshare:about' %}">About Us</a></li>
                    <li><a href="{% url 'flatshare:contact' %}">Contact Us</a></li>
                    
                    {% if user.is_authenticated %}
                        <li style = "float:right"><a href="{% url 'flatshare:view_profile' user_slug=user %}">My Profile</a></li>
                        <li style = "float:right"><a href="{% url 'flatshare:my_matches' %}">My Matches</a></li>
                        <li style = "float:right"><a href="{% url 'flatshare:logout' %}">Log out</a></li>
                    {% else %}
                        <li style = "float:right"><a href="{% url 'flatshare:login' %}">Log in</a></li>
                        <li style = "float:right"><a href="{% url 'flatshare:signup' %}">Sign up</a></li>
                    {% endif %}  
                </ul>
            </div>
        </div>
        <div class = "container">
            {% block body_block %}
            {% endblock %}
        </div>
        <div class="footer">
            <ul>
                <li><a href="{% url 'flatshare:index' %}">Terms Of Use</a></li>
                <li><a href="">Privacy Policy</a></li>
                <li class="right"><a href="{% url 'flatshare:about' %}">About Us</a></li>
                <li class="right"><a href="{% url 'flatshare:contact' %}">Contact Us</a></li>
            </ul>
        </div>
    </body>
</html>

templates/flatshare/change_password.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>flatshare - Change Password</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/change_password.css' %}">
{% endblock %}
{% block body_block %}
<div>
    <div class="login-form">
        <h2>Change your password</h2>
        <form class="login-form" id="password_form" method="post" action="{% url 'flatshare:change_password' user_slug=user.userprofile.slug%}" enctype="multipart/form-data">
            {% csrf_token %}
            <input type = "password" name = "password" placeholder = "Please enter your current password" size = 50><br/>
            <input type = "password" name = "new_password" placeholder = "Please enter your new password" size = 50><br/>
            <button  class="login-btn" type="submit">Change Password</button>
        </form>
    </div>
</div>
{% endblock %}

templates/flatshare/contact.html
<!DOCTYPE html>
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>flatshare - Contact Us</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block body_block %}
    <h1>How to Contact Us</h1>
	<img class = "contact-image" src="{% static 'images/phone_icon.png' %}" alt="Phone Icon"/>
    <div class = "main-contact">
        <h3>If you have any questions or would like to report any issues with the site please contact us on:</h3>
        <h5>Email: info@flatshare.co.uk</h5>
        <h5>Telephone: 0141 555 6677</h5>
        <h5>Post: 1, Buchanan Street, Glasgow, G1 1AA</h5>
    </div>
    <div class = "secondary-contact">
        <h3>Alternatively if you find an inappropriate, abusive or fake profile please use:</h3>
        <h5>Email: report@flatshare.co.uk</h5>
        <h5>Telephone: 0141 999 0999</h5>
    </div>
{% endblock %}

templates/flatshare/flat.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>Flatshre - {{flat.owner}}'s Flat</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/flat.css' %}">
{% endblock %}

{% block body_block %}
<div>
{% if flat %}
    <h3>{{ flat.name }}</h3>
    <div class = "info">
        <ul>
            <li>Address: {{ flat.address }}</li>
            <li>PPM: {{ flat.rent }}</li>
            <li>Owner: {{ flat.owner }}</li>
            <li>Available From: {{ flat.available_from }}</li>
            <li>{{ flat.description }}</li>
        </ul>
    </div>
    <div class = "img1-div">
        <img src="{{ MEDIA_URL }}{{ flat.save_location }}{{ flat.image1.name }}">
    </div>
    <div class = "img2-div">
        <img src="{{ MEDIA_URL }}{{ flat.image2 }}">
    </div>
    <form action='like' method='GET'>
        <button type='submit'> Like Flat </button>
    </form>
{% else %}
    <strong>There are no flats present.</strong>
{% endif %}
</div>
{% endblock %}

templates/flatshare/flats.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>Flatshare - Available Flats</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/flats.css' %}">
{% endblock %}

{% block body_block %}
    <h1>Available Flats</h1>
    <div class = "content">
    {% if flats %}
        <ul>
        {% for flat in flats %}
            <div class = "flat">
                <li>{{ flat }}</li><br/>
                <p><a href="{{ flat.slug }}/">Details...</a></p><br />
            </div>
        {% endfor %}
        </ul>
    {% else %}
        <h3>There are no flats present.</h3>
    {% endif %}
        <p><a href="/">Back to Home</a></p><br />
    </div>
{% endblock %}

templates/flatshare/index.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
	<title>flatshare - home</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock %}

{% block body_block %}
	<div class="homeImage">
		<img src="{% static 'images/apartment1.jpg' %}" alt="picture of room"/>
	</div>

	<div class="content1">
		<h1> Share A Flat</h1>
	</div>
	<div class="content2">
		<h2 name="about_us">Our Services</h2>
		<div class='par-1'>
			<h3>Service 1</h3>
			<p>
				Lorem ipsum dolor sit amet, <br/>
				consectetur adipiscing elit, sed do eiusmod<br/>
				tempor incididunt ut labore et dolore magna aliqua.<br/>
				ad minim veniam, quis nostrud exercitation ullamco <br/>
				aliquip ex ea commodo consequat. Duis aute <br/>
				irure dolor in reprehenderit in velit <br/>
				esse cillum dolore eu fugiat nulla<br/>
				pariatur. Excepteur sint occaecat <br/>
				cupidatat non proident, sunt <br/>
				in culpa qui officia <a href="">Link</a>.
			</p>
		</div>
		<div class='par-2'>
			<h3>Service 2</h3>
			<p>
				Lorem ipsum dolor sit amet, <br/>
				consectetur adipiscing elit, sed do eiusmod<br/>
				tempor incididunt ut labore et dolore magna aliqua.<br/>
				ad minim veniam, quis nostrud exercitation ullamco <br/>
				aliquip ex ea commodo consequat. Duis aute <br/>
				irure dolor in reprehenderit in velit <br/>
				esse cillum dolore eu fugiat nulla<br/>
				pariatur. Excepteur sint occaecat <br/>
				cupidatat non proident, sunt <br/>
				in culpa qui officia <a href="">Link</a>.
			</p>
		</div>
		<div class='par-3'>
			<h3>Service 3</h3>
			<p>
				Lorem ipsum dolor sit amet, <br/>
				consectetur adipiscing elit, sed do eiusmod<br/>
				tempor incididunt ut labore et dolore magna aliqua.<br/>
				ad minim veniam, quis nostrud exercitation ullamco <br/>
				aliquip ex ea commodo consequat. Duis aute <br/>
				irure dolor in reprehenderit in velit <br/>
				esse cillum dolore eu fugiat nulla<br/>
				pariatur. Excepteur sint occaecat <br/>
				cupidatat non proident, sunt <br/>
				in culpa qui officia <a href="">Link</a>.
			</p>
		</div>
	</div>
{% endblock %}

templates/flatshare/login.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %} 

{% block head_block %}
    <title>flatshare - login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body_block %}
<div>
    <div class = "login-form">
        <h2>Login to Flatshare</h2>
        <form id ="login_form" method = "post" action = "{% url 'flatshare:login' %}">
            {% csrf_token %}
            <input type= "text" name="username" placeholder = "Enter Username" size = "50">
            <br />
            <input type= "password" name="password" placeholder = "Enter Password" size = "50">
            <br />
            <button  class="login-btn" type="submit">Login</button>
            <br />
        </form> 
    </div>
    <div class='signup'>
        <p>Don't have an account? <a href="{% url 'flatshare:signup' %}">Sign up</a></p>
    </div>
</div>

{% endblock %}

templates/flatshare/matches.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>Flatshare - {{ user }}'s Matches </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/matches.css' %}">
{% endblock %}

{% block body_block %}
    <div class = "your-matches">
        <h3>Your Matches</h3>
        {% if matches %}
            <li>
                {% for match in matches %}
                    <h5>{{ match }}<h5>
                {% endfor %}
            </li>
        {% else %}
            <h5>No flat matches available</h5>
        {% endif %}
    </div>
    <div class = "your-likes">
        <h3>Users who have liked your flat:</h3>
        {% if likers %}
            {% for liker in likers%}
                <h5><a href="{% url 'flatshare:view_profile' user_slug=liker.slug%}">{{ liker.user }}</a><h5>
                <form action='{{ liker.slug }}/like' method='GET'>
                    <button type='submit'> Like User </button>
                </form>
            {% endfor %}
        {% else %}
            <h5>No one has liked your flat yet.</h5>
        {% endif %}
    </div>
    <div class = "your-liked">
        <h3>Flats you've liked</h3>
        {% if likes %}
            {% for flat in likes%}
                <h5><a href="{% url 'flatshare:show_flat' flat_slug=flat.slug%}">{{ flat }}</a></h5>
                <form action='{{ flat.slug }}/unlike' method='GET'>
                    <button type='submit'> Unlike Flat </button>
                </form>
            {% endfor %}
        {% else %}
            <h5>You haven't liked any flats yet.</h5>
        {% endif %}
    </div>
{% endblock %}

templates/flatshare/signup.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>flatshare - Sign up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}
{% block body_block %}
<div>
    <h1>Register for Flatshare</h1>
    {%if registered %}
    <strong>thank you for registering!</strong>
    <a hreh="{% url 'flatshare:index' %}">Return Home.</a><br />
    {% else %}
    <div class="user-form">
        <form class="user-form" id="user_form" method="post" action="{% url 'flatshare:signup' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input class="register" type="submit" name="submit" value="Register" />
        </form>
    </div>
    {% endif %}
    <div class="login">
        <p>Already have an account? <a href="{% url 'flatshare:login'%}">Log in</a></p>
    </div>
</div>
{% endblock %}

templates/flatshare/user.html
{% extends 'flatshare/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <title>Flatshare - {{ user_profile.FirstName }}'s Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/user.css' %}">
{% endblock %}

{% block body_block %}
    <div>
        {% if user_profile %}
            <h1>{{ user_profile.FirstName }} {{ user_profile.LastName }}</h1>
            <img class="profile-picture" src="{{ MEDIA_URL }}{{ user_profile.picture }}">
            <div class="content1">
                <h3>Age: {{ user_profile.age }}</h3>
                <h3>Bio: {{ user_profile.bio }}</h3>
            </div>
            <div class="content2">
                <h3>Flats owned by the user</h3>
                {% if owned_flats %}
                    <ul>
                        <li>
                            {% for flat in owned_flats %}
                                {{ flat.name }}
                            {% endfor %}
                        </li>
                    </ul>
                {% else %}
                    <p>User doesn't own any flats</p>
                {% endif %}
            </div>
            <a href="{% url 'flatshare:change_password' user_slug=user_profile.slug%}">Change password</a>
        {% else %}
            <strong>User profile empty</strong>
        {% endif %}
    </div>
{% endblock %}